add rlens and IsLabel instance for lenses
turingjump/bookkeeper pull request #26
Opened 2016-12-05 17:53 UTC by glutamate

Inspired by the Rawr package (https://hackage.haskell.org/package/rawr), this PR adds:

* an `rlens` function that generates a lens from a record label
* an instance of IsLabel for lenses, so you can write `julian ^. #age` and `julian & #age .~ 29` by using the field labels directly as lenses and get all the goodies of you favourite lens library.

This does not add a dependency on a lens library, although the lenses are compatible with `lens` and `microlens` packages. Unfortunately without adding a dependency on one of these libraries I can't add doctests for the added functions.

Apparently the IsLabel instance is an orphan, so I have suppressed that warning.

2016-12-05 18:03 UTC, jkarni requested changes
Thanks a lot!

Because of the orphan instance, I'm inclined to say this should be kept in a separate module (`Bookkeeper.Lens`) and not exported from the `Bookkeeper` module since otherwise it'll be impossible to use with packages that declare a different instance (`rawr` for now, which I understand is unlikely to be used in conjunction with `bookkeeper`, but I imagine as `IsLabel` gets more popular other packages too).

I can take a look at whether we can add `microlens` just for the `doctest` test, but in either case, I'm okay with having this not doctested.

2016-12-05 18:17 UTC, glutamate commented
I have moved lensy stuff to Bookkeeper.Lens and figured out how to import microlens for the doctests only

2016-12-05 18:26 UTC, glutamate commented
Interesting, the doctests pass here as-is. I will remove them a bit later tonight as they are failing on CI.

2016-12-07 12:26 UTC, jkarni approved these changes

2016-12-07 12:26 UTC, merged

2016-12-07 12:27 UTC, jkarni commented
Thanks!

2016-12-07 12:29 UTC, jkarni commented
Released as version 0.2.4.